create or replace TRIGGER "USER_CUSTOMER_INSERTION" AFTER INSERT ON Users 
FOR EACH ROW

BEGIN

IF (:NEW.LOGIN_TYPE = 'CUSTOMER') THEN
    INSERT INTO 
    customers (NAME, CONTACT_NUMBER, ADDRESS, WALLET_ID, USER_ID)
    VALUES
    (:NEW.NAME, :NEW.CONTACT_NUMBER, :NEW.ADDRESS, customer_wallet_id_seq.nextval, :NEW.USER_ID);
END IF;

IF(:NEW.LOGIN_TYPE = 'BRAND') THEN
    INSERT INTO 
    brands (NAME, ADDRESS, JOIN_DATE, LOYALTY_TYPE, USER_ID)
    VALUES
    (:NEW.NAME, :NEW.ADDRESS, sysdate, null , :NEW.USER_ID);
END IF;

END;